#' Create EnrichmentMap in Cytoscape to visualize selection-enriched pathways
#'
#' @description Create a network where nodes are pathway gene sets significantly
#'		enriched in two independent population-based GSEA (i.e., validated
#' 		selection-enriched gene sets.) Pathways are then clustered to identify
#'		main pathways and themes of the selection-enriched gene sets.
#' @param gmtF (char) file path to GMT file (this needs to be absolute path name).
#' @param eMapF (char) file path to results_eMap.txt (generated by writeEmapFile.R).
#' @param outDir (char) file path to write gene set grouping file. This will be
#' 		used for between-pathway SNP association analysis.
#' @param netName (char) name for network in Cytoscape.
#' @param imageFormat (char) one of PNG, PDF, SVG, or JPEG.
#'
#' # not run because requires Cytoscape to be installed and open
#' # plotEmap(gmtFile = gmtF, nodeAttrFile = nodeAttrFile, netName="HighRisk",
#'	# outDir=outDir).
#' @return Filename of image to which EnrichmentMap is exported. Also side
#' 		effect of plotting the EnrichmentMap in an open session of Cytoscape.
#' @export
#'

plotEmap <- function(gmtF, eMapF, outDir,
									   netName="generic", imageFormat="png") {

	# Confirm that Cytoscape is installed and opened
	cytoscapeVersionInfo()

  # Create EM using given parameters
	if (netName %in% getNetworkList()) {
		deleteNetwork(netName)
	}

	cat("*Building the network\n")
	em_command <- paste('enrichmentmap build analysisType="generic"',
			'gmtFile=', pathF,
			'enrichmentsDataset1=', eMapF,
			'pvalue=', 1,
			'qvalue=', 1,
			'similaritycutoff=', 0.375,
			'coefficients=', "COMBINED",
		  'combinedConstant=', 0.5)
  response <- commandsGET(em_command)
	renameNetwork(netName, getNetworkSuid())

 	# Annotate the network using AutoAnnotate app
	cat("*Annotating the network using AutoAnnotate\n")
  aa_command <- paste("autoannotate annotate-clusterBoosted",
		"clusterAlgorithm=MCL",
		"maxWords=3",
		"network=", netName)
	#print(aa_command)
	response <- commandsGET(aa_command)

	# Apply style
	cat("*Creating or applying style\n")
  styleName <- "EMapStyle"
	defaults <- list("NODE_SHAPE"="ellipse",
  			"NODE_SIZE"=30,
  			"EDGE_TRANSPARENCY"=200,
  			"NODE_TRANSPARENCY"=255,
				"EDGE_STROKE_UNSELECTED_PAINT"="#999999") # get node colour in paper

	createVisualStyle(styleName, defaults)
	setVisualStyle(styleName)
	layoutNetwork("attributes-layout NodeAttribute=__mclCLuster")

	redraw_command <- sprintf("autoannotate redraw network=%s",getNetworkSuid())
  response <- commandsGET(redraw_command)
	fitContent()
  redraw_command <- sprintf("autoannotate redraw network=%s", getNetworkSuid())
  response <- commandsGET(redraw_command)
	fitContent()

	# Retrieve edge overlap data to reconstruct gene set clusters (i.e. pathways)
	edge <- commandsPOST("edge get attribute")
	edge_name <- as.data.frame(unlist(lapply(edge, '[', "name")))
	edge_name <- strsplit(as.character(edge_name[,1]), " \\(Geneset_Overlap_Dataset 1) ")

	# Initialize values
	len <- length(edge_name)
	ks <- NULL
	rem <- NULL

	for (i in 1:len) {
		int_k <- i+1
		if (int_k > len) {
			cat("*Merged pathway list generated\n")
			break
		}
		for (k in int_k:len) {
			if (length(which(edge_name[[i]] %in% edge_name[[k]])) >= 1) {
				edge_name[[i]] <- union(edge_name[[i]], edge_name[[k]])
			}
			ks <- c(ks, k)
		}
		for (j in ks) {
			if (length(which(edge_name[[i]] %in% edge_name[[j]])) >= 1) {
				rem <- c(rem, j)
			}
		}
		if (length(rem)) {
			edge_name <- edge_name[-rem]
		}
		len <- length(edge_name)
		rem <- NULL
		ks <- NULL
	}

	pathways <- edge_name

	# Retrieve node data to get un-annotated gene sets (single pathways)
	node <- commandsPOST("node get attribute")
	node_name <- as.data.frame(unlist(lapply(node, '[', "name")))
	node_name <- as.character(node_name[,1])

	# Create crude pathway names by selecting top 3 words in pathway group
	# NOTE potential future update of Cytoscape API to retrieve nodes in AutoAnnotate clusters
	single_path <- node_name[-which(node_name %in% unlist(pathways))]
	pathway_groups <- c(pathways, single_path)

	for (x in seq_along(pathway_groups)) {
		path <- gsub("\\%.*", "", pathway_groups[[x]])
		path_split <- unlist(strsplit(path, " "))
		# Remove small words (to omit words such as "of", "the", "as", etc)
		if (length(path_split) > 3) {
			small_words <- which(nchar(path_split) <= 3)
			if (length(small_words)) {
				path_split <- path_split[-small_words]
			}
			top <- sort(table(path_split), decreasing=TRUE)[1:3]
			names(pathway_groups)[x] <- paste(names(top), collapse="_")
		}
		else {
			names(pathway_groups)[x] <- paste(path_split, collapse="_")
		}
	}

	# Write out rda file with pathway groupings
	save(pathway_groups, file=sprintf("%s/pathway_groups.rda", outDir))

	# Write out EnrichmentMap to eMapF directory
	outF <- substr(eMapF, 0, nchar(eMapF)-4)
	exportImage(outF, type=imageFormat)
	return(outF)
}
