#' Create EnrichmentMap in Cytoscape to visualize selection-enriched pathways
#'
#' @description Create a network where nodes are pathway gene sets significantly
#'		enriched in two independent population-based GSEA (i.e., validated
#' 		selection-enriched gene sets.) Pathways are then clustered to identify
#'		main pathways and themes of the selection-enriched gene sets.
#' @param gmtF (char) file path to GMT file (this needs to be absolute path name).
#' @param resF (list) file paths to results_forEM.txt for each population comparison
#' 		(generated by setupGSEA_run.R).
#' @param netName (char) name for network in Cytoscape.
#' @param outDir (char) path to directory where file should be stored.
#' @param imageFormat (char) one of PNG, PDF, SVG, or JPEG.
#' @param verbose (logical) print messages.
#'
#' # not run because requires Cytoscape to be installed and open
#' # plotEmap(gmtFile = gmtF, nodeAttrFile = nodeAttrFile, netName="HighRisk",
#'	# outDir=outDir).
#' @return Filename of image to which EnrichmentMap is exported. Also side
#' 		effect of plotting the EnrichmentMap in an open session of Cytoscape.
#' @export
#'

plotEmap <- function(gmtF, resF, netName="generic", outDir,
										 imageFormat="png", verbose=FALSE) {


	# Confirm that Cytoscape is installed and opened
	cytoscapeVersionInfo()

	#######################################
  #create EM using given parameters
  #######################################
	if (netName %in% getNetworkList()) {
		deleteNetwork(netName)
	}

	####
  gmtF <- "/Users/catherineross/POPPATHR/anno/Human_GOBP_AllPathways_no_GO_iea_April_24_2016_symbol.gmt"
	resDirs <- list.files(pattern="*out", path="/Users/catherineross/POPPATHR", full.names=T)
	resF <- list.files(pattern="results_forEM", path=sprintf("%s/gsea", resDirs), full.names=TRUE)
	####

	em_command <- paste('enrichmentmap build analysisType="generic"',
			'gmtFile=', gmtF,
			'enrichmentsDataset1=', resF[1],
			'pvalue=', 1,
			'qvalue=', 1,
			'similaritycutoff=', 0.375,
			'coefficients=', "COMBINED",
		  'combinedConstant=', 0.5)
  response <- commandsGET(em_command)
	renameNetwork(netName, getNetworkSuid())

 # Annotate the network using AutoAnnotate app
  aa_command <- paste("autoannotate annotate-clusterBoosted",
		"clusterAlgorithm=MCL",
	  "labelColumn=name",
		"maxWords=3",
		"network=", netName)
	print(aa_command)
	response <- commandsGET(aa_command)

	# Apply style
	cat("* Creating or applying style\n")
  all_unique_scores_int <- sort(unique(read.delim(enrichPathF)[,2]))
  all_unique_scores <- unlist(lapply(all_unique_scores_int, toString))
  styleName <- "EMapStyle"

	nodeLabels <- mapVisualProperty('node label','name','p')
	nodeFills <- mapVisualProperty('node fill color','maxScore','d', ## NOTE remove maxScore
			scoreVals,style_cols)
 		defaults <- list("NODE_SHAPE"="ellipse",
  			"NODE_SIZE"=30,
  			"EDGE_TRANSPARENCY"=200,
  			"NODE_TRANSPARENCY"=255,
				"EDGE_STROKE_UNSELECTED_PAINT"="#999999")
	if (createStyle) {
		cat("Making style\n")
		createVisualStyle(styleName,defaults, list(nodeLabels,nodeFills))
	}

	setVisualStyle(styleName)
	layoutNetwork("attributes-layout NodeAttribute=__mclCLuster")
  redraw_command <- sprintf("autoannotate redraw network=%s",getNetworkSuid())
  response <- commandsGET(redraw_command)
	fitContent()
  redraw_command <- sprintf("autoannotate redraw network=%s",getNetworkSuid())
  response <- commandsGET(redraw_command)
	fitContent()

	outFile <- sprintf("EMap_%s", netName)
	exportImage(outFile, type=imageFormat)
	return(outFile)
}
