#' Plots an EnrichmentMap in Cytoscape to visualize selection-enriched pathways
#'
#' @description Create a network where nodes are pathway gene sets significantly
#' enriched in two independent population-based GSEA (i.e., validated
#' selection-enriched gene sets.) Pathways are then clustered to identify
#' main pathways and themes of the selection-enriched gene sets.
#' @param gmtFile (char) file path to GMT file (this needs to be absolute path name).
#' @param emFile (char) file path to results_EM.txt (generated by writeEmapFile.R).
#' @param emGroupFile (char) file path to write pathway groupings as determined
#' by EnrichmentMap.
#' @param pvalue (numeric) pvalue cutoff (value between 0 and 1; default 1)
#' @param qvalue (numeric) qvalue cutoff (value between 0 and 1; default 1)
#' @param formSim (character) formula to calculate similarity score
#' (one of OVERLAP, JACCARD, COMBINED; default COMBINED)
#' @param edgeSim (numeric) edge similarity score cutoff
#' (value between 0 and 1; default 0.375)
#' @param combSim (numeric) when coefficients=COMBINED this parameter is used
#' to determine what percentage to use for JACCARD and OVERLAP when combining
#' their value (value between 0 to 1; default 0.5)
#' @param chartData (char) node chart data (one of NES_VALUE, P_VALUE,
#' FDR_VALUE, PHENOTYPES, DATA_SET, EXPRESSION_SET, or NONE;
#' default NES_VALUE)
#' @param clustAlg (character) clusterMaker algorith
#' (one of AFFINITY_PROPAGATION, CLUSTER_FIZZIFIER, GLAY, CONNECTED_COMPONENTS,
#' MCL, SCPS; default MCL)
#' @param clustWords (integer) maximum words to include in autoAnnotate
#' cluster label (default 3)
#' @param netName (char) name for network in Cytoscape.
#' @param netFile (char) one of PNG, PDF, SVG, or JPEG.
#' @return Filename of image to which EnrichmentMap is exported. Also side
#' effect of plotting the EnrichmentMap in an open session of Cytoscape.
#' @export
plotEmap <- function(gmtFile, emFile, emGroupFile, pvalue=1, qvalue=1,
	formSim="COMBINED", edgeSim=0.375, combSim=0.5,
	chartData="NES_VALUE", clustAlg="MCL", clustWords=3,
	netName="generic", netFile="png") {

	emap <- tryCatch({
			# Confirm that Cytoscape is installed and opened
			cytoscapePing()
		  	# Create EM using given parameters
			if (netName %in% getNetworkList()) {
				deleteNetwork(netName)
			}

			######
			# BUILD ENRICHMENT MAP
			######

			cat("* Building the network\n")
			em_command <- paste0(
				"enrichmentmap build analysisType=generic",
				" networkName=", netName,
				" gmtFile=", gmtFile,
				" enrichmentsDataset1=", emFile,
				" pvalue=", pvalue,
				" qvalue=", qvalue,
				" coefficients=", formSim,
				" similaritycutoff=", edgeSim,
				" combinedConstant=", combSim
			)
			response <- commandsPOST(em_command)

	 		# Annotate the network via AutoAnnotate
			cat("* Annotating the network via AutoAnnotate\n")
			aa_command <- paste0(
				"autoannotate annotate-clusterBoosted",
				" clusterAlgorithm=", clustAlg,
				" maxWords=", clustWords,
				" network=", netName
			)
			response <- commandsPOST(aa_command)

			# Apply style
			#cat("* Creating or applying style\n")
	  		#styleName <- "EMapStyle"
			#defaults <- list(
			#	"NODE_SHAPE"="ellipse",
	  		#	"NODE_SIZE"=30,
	  		#	"EDGE_TRANSPARENCY"=200,
	  		#	"NODE_TRANSPARENCY"=255,
			#	"EDGE_STROKE_UNSELECTED_PAINT"="#999999"
			#) # get node colour in paper
			#createVisualStyle(styleName, defaults)
			#setVisualStyle(styleName)

			# Apply layout
			cat("* Applying layout\n")
			layoutNetwork("attributes-layout NodeAttribute=__mclCLuster")
			redraw_command <- sprintf("autoannotate redraw network=%s", getNetworkSuid())
		  	response <- commandsGET(redraw_command)
			fitContent()

			######
			# PULL TABULAR FORMAT OF PATHWAY CLUSTERS
			######

			# Pull node names from AutoAnnotated clusters
			# Get node and edge table that have the cluster annotations
			nodeTable <- getTableColumns(table="node", network=getNetworkSuid())
			edgeTable <- getTableColumns(table="edge", network=getNetworkSuid())

			# Get the correct attribute names
			descrAttrib <- colnames(nodeTable)[grep(colnames(nodeTable), pattern="GS_DESCR")]

			# Get all the cluster numbers
			clusterNum <- nodeTable$'__mclCluster'

			# Get the unique set of clusters
			setClusters <- unique(clusterNum)
			setClusters <- setClusters[which(setClusters != 0)]

			# Calculate the cluster names using AutoAnnotate and collate all the nodes
			# associated with each cluster
			clusterNames <- c()
			for (i in 1:length(setClusters)) {
				currentCluster <- setClusters[i]
			  	gsCluster <- nodeTable$name[which(nodeTable$'__mclCluster' == currentCluster)]

			  	# For this cluster of gs get the gs descr to use in defining in AutoAnnotate
			  	gsClusterSUID <- nodeTable$SUID[which(nodeTable$name %in% gsCluster)]
			  	SUIDaa <- paste("SUID", gsClusterSUID, sep=":")

			  	# Get the annotation for the given cluster
			  	curerntName = NULL
			  	aaLabel <- paste(
					"autoannotate label-clusterBoosted",
				  	"labelColumn=", descrAttrib,
				  	"maxWords=3",
				  	"nodeList=", paste(SUIDaa, collapse=",")
			  	)
			  	currentName <- commandsGET(aaLabel)
			  	clusterNames <- rbind(clusterNames,
					c(currentCluster, currentName,
					length(gsCluster), paste(gsCluster, collapse=";"))
				)
			}

			# Create list of cluster names and associated pathways
			emGroupList <- list()
			for (k in 1:nrow(clusterNames)) {
				emGroupList[[k]] <- unlist(strsplit(clusterNames[k,4], ";"))
				names(emGroupList)[k] <- gsub(" ", "_", toupper(clusterNames[k,2]))
			}
			# Get single unclustered gene sets and add to list
			singlePath <- nodeTable[-which(nodeTable$name %in% unlist(emGroupList)),]$name

			# Remove annotation info from gene set names
			singlePathName <- gsub("\\%.*", "", singlePath)
			singlePathName <- gsub(" ", "_", singlePathName)
			names(singlePath) <- singlePathName

			# Add to existing list
			emGroupList <- c(emGroupList, singlePath)

			# Write out rda file with pathway EM groupings
			save(emGroupList, file=emGroupFile)
		},
		error = function(x) {
			return(NULL)
		})
	return(emap)
}
