#' Write enrichments file for use in Cytoscape EnrichmentMap
#'
#' @param resEmF (list) file paths to results_forEM.txt for each population comparison
#' 		(generated by setupGSEA_run.R).
#' @param enrichNES (integer) NES cutoff to select validated selection-enriched
#'		pathways (default=0.3)
#' @param outDir (char) path to directory where file should be stored.
#'
#' @return none
#' @export
#'

writeEmapFile <- function(resEmF, enrichNES=0.3, outDir) {
  # Read in GSEA results files formatted for EnrichmentMap
  EMfiles <- lapply(resEmF, function(x) read.delim(x, h=TRUE, as.is=TRUE))
  EM_comb <- join_all(EMfiles, by=c("Geneset", "Description"))
}
