#' Write enrichments file for use in Cytoscape EnrichmentMap
#'
#' @param resF (list) file paths to results.txt for each population comparison
#' 		(generated by setupGSEA_run.R).
#' @param enrichNES (integer) NES cutoff to select validated selection-enriched
#'		pathways (default=3)
#' @param outF (char) name of output file.

#' @return none. Output file write into directory of first population comparison.
#'    E.g., CEU_YRI directory
#' @export
#'

writeEmapFile <- function(resF, enrichNES=3, outF) {
  # Read in GSEA results files formatted for EnrichmentMap
  resFiles <- lapply(resF, function(x) read.delim(x, h=TRUE, as.is=TRUE))
  for (i in seq_along(resFiles)) {
    resFiles[[i]] <- resFiles[[i]][,c(1,1,5,6,4)]
    colnames(resFiles[[i]])[2] <- "Description"
    colnames(resFiles[[i]])[3:5] <- paste(colnames(resFiles[[i]][, c(3:5)]), i, sep="_")
  }
  resComb <- join_all(resFiles, by=c("Geneset", "Description"))
  # Select for enriched pathways
  resComb_enrich <- filter(resComb, NES_1 >= enrichNES & FDR_1 <= 0.05)
  if (length(resFiles) > 1) { # filter by second population analysis if run
    resComb_enrich <- filter(resComb_enrich, NES_2 >= enrichNES & FDR_2 <= 0.05)
  }
  # Remove gene set annotation details from Description column
  ## Needed for AutoAnnotate app to properly annotate aggregated gene sets
  resComb_enrich$Description <- gsub("\\%.*", "", resComb_enrich$Description)
  # Write out file for EnrichmentMap input
  EMout <- resComb_enrich[,c(1:4)]
  write.table(EMout, outF, col=TRUE, row=FALSE, quote=FALSE, sep="\t")
}
