# [workdir]/ld/hc_snps
require(plyr)
require(xlsx)

dat <- read.delim("gseaStat_per_hc_pathway.txt", h=T, as.is=T)
paths <- read.delim("pathways_hc.txt", h=F, as.is=T)
colnames(paths) <- "pathway_name"
paths$pathway <- as.integer(rownames(paths))

blah <- join(dat, paths, by="pathway")
blah <- blah[,-4]
colnames(blah)[5] <- "pathway"

blah$cluster <- NA

blah$cluster[blah$pathway=="CELL CHEMOTAXIS%GOBP%GO:0060326"|
             blah$pathway=="CHEMOTAXIS%GOBP%GO:0006935"|
             blah$pathway=="TAXIS%GOBP%GO:0042330"] = "CELL CHEMOTAXIS"
blah$cluster[blah$pathway=="CELLULAR RESPONSE TO LIGHT STIMULUS%GOBP%GO:0071482"|
             blah$pathway=="CELLULAR RESPONSE TO RADIATION%GOBP%GO:0071478"] = "CELLULAR RESPONSE TO LIGHT"
blah$cluster[blah$pathway=="BMP SIGNALING PATHWAY%GOBP%GO:0030509"|
             blah$pathway=="CELLULAR RESPONSE TO BMP STIMULUS%GOBP%GO:0071773"|
             blah$pathway=="CELLULAR RESPONSE TO GROWTH FACTOR STIMULUS%GOBP%GO:0071363"|
             blah$pathway=="REGULATION OF PATHWAY-RESTRICTED SMAD PROTEIN PHOSPHORYLATION%GOBP%GO:0060393"|
             blah$pathway=="RESPONSE TO BMP%GOBP%GO:0071772"|
             blah$pathway=="RESPONSE TO GROWTH FACTOR%GOBP%GO:0070848"|
             blah$pathway=="SIGNALING BY BMP%REACTOME DATABASE ID RELEASE 56%201451"|
             blah$pathway=="SMAD PROTEIN SIGNAL TRANSDUCTION%GOBP%GO:0060395"|
             blah$pathway=="TRANSMEMBRANE RECEPTOR PROTEIN SERINE/THREONINE KINASE SIGNALING PATHWAY%GOBP%GO:0007178"] = "GROWTH FACTOR AND BMP SIGNALLING"
blah$cluster[blah$pathway=="REGULATION OF HEMOPOIESIS%GOBP%GO:1903706"|
             blah$pathway=="REGULATION OF MYELOID CELL DIFFERENTIATION%GOBP%GO:0045637"|
             blah$pathway=="REGULATION OF MYELOID LEUKOCYTE DIFFERENTIATION%GOBP%GO:0002761"] = "IMMUNE CELL REGULATION"
blah$cluster[blah$pathway=="POSITIVE REGULATION OF CELL MIGRATION%GOBP%GO:0030335"|
             blah$pathway=="POSITIVE REGULATION OF CELL MOTILITY%GOBP%GO:2000147"|
             blah$pathway=="POSITIVE REGULATION OF LEUKOCYTE MIGRATION%GOBP%GO:0002687"] = "REGULATION OF CELL MIGRATION"
blah$cluster[blah$pathway=="POSITIVE REGULATION OF LIPID METABOLIC PROCESS%GOBP%GO:0045834"|
             blah$pathway=="REGULATION OF LIPID METABOLIC PROCESS%GOBP%GO:0019216"] = "REGULATION OF LIPID METABOLISM"
blah$cluster[blah$pathway=="3' -UTR-MEDIATED TRANSLATIONAL REGULATION%REACTOME DATABASE ID RELEASE 56%157279"|
             blah$pathway=="CAP-DEPENDENT TRANSLATION INITIATION%REACTOME DATABASE ID RELEASE 56%72737"|
             blah$pathway=="COTRANSLATIONAL PROTEIN TARGETING TO MEMBRANE%GOBP%GO:0006613"|
             blah$pathway=="ESTABLISHMENT OF PROTEIN LOCALIZATION TO ORGANELLE%GOBP%GO:0072594"|
             blah$pathway=="EUKARYOTIC TRANSLATION ELONGATION%REACTOME DATABASE ID RELEASE 56%156842"|
             blah$pathway=="EUKARYOTIC TRANSLATION INITIATION%REACTOME DATABASE ID RELEASE 56%72613"|
             blah$pathway=="EUKARYOTIC TRANSLATION TERMINATION%REACTOME DATABASE ID RELEASE 56%72764"|
             blah$pathway=="FORMATION OF A POOL OF FREE 40S SUBUNITS%REACTOME DATABASE ID RELEASE 56%72689"|
             blah$pathway=="GTP HYDROLYSIS AND JOINING OF THE 60S RIBOSOMAL SUBUNIT%REACTOME%R-HSA-72706.1"|
             blah$pathway=="L13A-MEDIATED TRANSLATIONAL SILENCING OF CERULOPLASMIN EXPRESSION%REACTOME%R-HSA-156827.1"|
             blah$pathway=="NONSENSE MEDIATED DECAY (NMD) ENHANCED BY THE EXON JUNCTION COMPLEX (EJC)%REACTOME DATABASE ID RELEASE 56%975957"|
             blah$pathway=="NONSENSE MEDIATED DECAY (NMD) INDEPENDENT OF THE EXON JUNCTION COMPLEX (EJC)%REACTOME%R-HSA-975956.1"|
             blah$pathway=="NONSENSE-MEDIATED DECAY (NMD)%REACTOME%R-HSA-927802.1"|
             blah$pathway=="PEPTIDE CHAIN ELONGATION%REACTOME%R-HSA-156902.1"|
             blah$pathway=="PROTEIN IMPORT INTO NUCLEUS%GOBP%GO:0006606"|
             blah$pathway=="PROTEIN TARGETING TO ER%GOBP%GO:0045047"|
             blah$pathway=="PROTEIN TARGETING TO NUCLEUS%GOBP%GO:0044744"|
             blah$pathway=="SELENOCYSTEINE SYNTHESIS%REACTOME DATABASE ID RELEASE 56%2408557"|
             blah$pathway=="SINGLE-ORGANISM NUCLEAR IMPORT%GOBP%GO:1902593"|
             blah$pathway=="SRP-DEPENDENT COTRANSLATIONAL PROTEIN TARGETING TO MEMBRANE%GOBP%GO:0006614"|
             blah$pathway=="VIRAL MRNA TRANSLATION%REACTOME%R-HSA-192823.1"] = "VIRAL TRANSLATION AND PROTEIN TARGETING"
blah$cluster[blah$pathway=="CA2+ PATHWAY%REACTOME DATABASE ID RELEASE 56%4086398"|
             blah$pathway=="WNT SIGNALING PATHWAY%GOBP%GO:0016055"] = "WNT CALCIUM SIGNALLING"
blah$cluster[blah$pathway=="ALPHA6BETA4INTEGRIN%IOB%ALPHA6BETA4INTEGRIN"] = "ALPHA6BETA4INTEGRIN"
blah$cluster[blah$pathway=="CARBOHYDRATE TRANSPORT%GOBP%GO:0008643"] = "CARBOHYDRATE TRANSPORT"
blah$cluster[blah$pathway=="CELL FATE COMMITMENT%GOBP%GO:0045165"] = "CELL FATE COMMITMENT"
blah$cluster[blah$pathway=="CHROMATIN SILENCING%GOBP%GO:0006342"] = "CHROMATIN SILENCING"
blah$cluster[blah$pathway=="EMBRYONIC MORPHOGENESIS%GOBP%GO:0048598"] = "EMBRYONIC MORPHOGENESIS"
blah$cluster[blah$pathway=="FC RECEPTOR SIGNALING PATHWAY%GOBP%GO:0038093"] = "FC RECEPTOR SIGNALLING PATHWAY"
blah$cluster[blah$pathway=="ID%IOB%ID"] = "ID SIGNALLING"
blah$cluster[blah$pathway=="IL4-MEDIATED SIGNALING EVENTS%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%IL4-MEDIATED SIGNALING EVENTS"] = "IL4-MEDIATED SIGNALLING EVENTS"
blah$cluster[blah$pathway=="PROTEASOMAL PROTEIN CATABOLIC PROCESS%GOBP%GO:0010498"] = "PROTEASOMAL PROTEIN CATABOLIC PROCESS"
blah$cluster[blah$pathway=="SENSORY ORGAN DEVELOPMENT%GOBP%GO:0007423"] = "SENSORY ORGAN DEVELOPMENT"
blah$cluster[blah$pathway=="VALIDATED NUCLEAR ESTROGEN RECEPTOR ALPHA NETWORK%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%VALIDATED NUCLEAR ESTROGEN RECEPTOR ALPHA NETWORK"] = "VALIDATED NUCLEAR ESTROGEN RECEPTOR ALPHA NETWORK"
